#!/command/with-contenv bash

bootstrap_filesystem() {
    if [ ! -d "${CONFIG_PATH}" ] ; then
        mkdir -p "${CONFIG_PATH}"
    fi
    if [ "$(stat -c %U "${CONFIG_PATH}")" != "homeassistant" ] ; then silent chown -R homeassistant:homeassistant "${CONFIG_PATH}" ; fi
    if [ "$(stat -c %a "${CONFIG_PATH}")" != "755" ] ; then chmod -R 755 "${CONFIG_PATH}" ; fi

    if [ ! -d "${CONFIG_CUSTOM_PATH}" ] ; then
        mkdir -p "${CONFIG_CUSTOM_PATH}"
    fi
    if [ "$(stat -c %U "${CONFIG_CUSTOM_PATH}")" != "homeassistant" ] ; then silent chown -R homeassistant:homeassistant "${CONFIG_CUSTOM_PATH}" ; fi
    if [ "$(stat -c %a "${CONFIG_CUSTOM_PATH}")" != "755" ] ; then chmod -R 755 "${CONFIG_CUSTOM_PATH}" ; fi

    if [ ! -d "${DATA_PATH}" ] ; then
        mkdir -p "${DATA_PATH}"
    fi
    if [ "$(stat -c %U "${DATA_PATH}")" != "homeassistant" ] ; then chown -R homeassistant:homeassistant "${DATA_PATH}" ; fi
    if [ "$(stat -c %a "${DATA_PATH}")" != "700" ] ; then chmod -R 700 "${DATA_PATH}" ; fi

    if [ "$(stat -c %U "${LOG_PATH}")" != "homeassistant" ] ; then chown homeassistant:homeassistant "${LOG_PATH}" ; fi
}
