#!/command/with-contenv bash

CONFIG_PATH=${CONFIG_PATH:-"/config/"}
ENABLE_JEMALLOC=${ENABLE_JEMALLOC:-"TRUE"}
LISTEN_PORT=${LISTEN_PORT:-"8123"}
LOG_PATH=${LOG_PATH:-"/logs/"}
LOG_FILE=${LOG_FILE:-"homeassistant.log"}
