#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
SERVICE_NAME=homeassistant

cat <<EOF

***************************************************************************************************
*                                                                                                 *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                           *
*                               tiredofit/homeassistant                                           *
*                                                                                                 *
* This image is no longer maintained as of and will not receive updates.                          *
*                                                                                                 *
* A successor image is available at:                                                              *
*                                                                                                 *
* Repository | Documentation:                                                                     *
*   - https://github.com/nfrastack/container-homeassistant                                        *
*                                                                                                 *
* Image Registries:                                                                               *
*   - https://hub.docker.com/r/nfrastack/homeassistant                                            *
*   - https://github.com/nfrastack/container-homeassistant/pkgs/container/container-homeassistant *
*                                                                                                 *
* Please visit https://nfrastack.com for more information.                                        *
*                                                                                                 *
***************************************************************************************************

EOF

sleep 15
bootstrap_filesystem
configure_webserver

liftoff