services:
  homeassistant-app:
    container_name: homeassistant-app
    image: docker.io/nfrastack/homeassistant:latest
    ports:
      - 8123:8123
      - 8000:80
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - SETUP_MODE=TRUE
    networks:
      - services
    restart: always

networks:
  services:
    external: true
