#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 20-homeassistant
PROCESS_NAME="homeassistant"

check_container_initialized
check_service_initialized init

liftoff

if var_true "${ENABLE_JEMALLOC}" ; then
  export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"
  export MALLOC_CONF="background_thread:true,metadata_thp:auto,dirty_decay_ms:20000,muzzy_decay_ms:20000"
fi

if [ "${LOG_LEVEL,,}" = "verbose" ]; then
    log_level="--verbose"
fi

case "${HOMEASSISTANT_MODE,,}" in
    debug)
        homeassistant_mode="--debug"
    ;;
    normal)
        :
    ;;
    recovery)
        homeassistant_mode="--recovery-mode"
    ;;
    *)
        :
    ;;
esac

if var_true "${SKIP_PIP,,}" ; then skip_pip="--skip-pip"; fi

print_start "Starting Home Assistant ${HOMEASSISTANT_VERSION}"

exec sudo -u "${HOMEASSISTANT_USER}" \
            /opt/homeassistant/bin/python3 \
                -m homeassistant \
                --config "${CONFIG_PATH}" \
                --log-rotate-days 0 ${log_level} \
                --log-file "${LOG_PATH}"/"${LOG_FILE}" \
                ${skip_pip} ${homeassistant_mode} ${HOMEASSISTANT_ARGS}
